apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lemonade-stand-secrets
spec:
  refreshInterval: {{ .Values.lemonadeStandSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: lemonade-stand-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        vllm-api-key: "{{ `{{ .vllmApiKey }}` }}"
  data:
    - secretKey: vllmApiKey
      remoteRef:
        key: {{ .Values.lemonadeStandSecret.key }}
        property: vllm-api-key
